services:
  - type: web
    name: moviezone
    runtime: node
    rootDir: moviebox-api1-main
    buildCommand: cd .. && npm install && npm run build && cd moviebox-api1-main && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_API_URL
        value: /api
